### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by ghost** [greentowngg/Virtueller-Apero-IOS-App#1]
Ein Chat wäre gut. Dann können die Teilnehmer der Virtual Aperp Gruppe chatten

**Comment by greentowngg** [comment]
timeline mit allen vergangenen Apéros

**Comment by hagengraf** [comment]
Die Timeline ist ein eigenes Issue ...

**Comment by ghost** [comment]
habe das issue auf das neue repository übertragen
